/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Certificate } from "./Certificate";
import { CertificateCountArgs } from "./CertificateCountArgs";
import { CertificateFindManyArgs } from "./CertificateFindManyArgs";
import { CertificateFindUniqueArgs } from "./CertificateFindUniqueArgs";
import { CreateCertificateArgs } from "./CreateCertificateArgs";
import { UpdateCertificateArgs } from "./UpdateCertificateArgs";
import { DeleteCertificateArgs } from "./DeleteCertificateArgs";
import { SoftwareProjectFindManyArgs } from "../../softwareProject/base/SoftwareProjectFindManyArgs";
import { SoftwareProject } from "../../softwareProject/base/SoftwareProject";
import { CertificateService } from "../certificate.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Certificate)
export class CertificateResolverBase {
  constructor(
    protected readonly service: CertificateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "read",
    possession: "any",
  })
  async _certificatesMeta(
    @graphql.Args() args: CertificateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Certificate])
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "read",
    possession: "any",
  })
  async certificates(
    @graphql.Args() args: CertificateFindManyArgs
  ): Promise<Certificate[]> {
    return this.service.certificates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Certificate, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "read",
    possession: "own",
  })
  async certificate(
    @graphql.Args() args: CertificateFindUniqueArgs
  ): Promise<Certificate | null> {
    const result = await this.service.certificate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Certificate)
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "create",
    possession: "any",
  })
  async createCertificate(
    @graphql.Args() args: CreateCertificateArgs
  ): Promise<Certificate> {
    return await this.service.createCertificate({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Certificate)
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "update",
    possession: "any",
  })
  async updateCertificate(
    @graphql.Args() args: UpdateCertificateArgs
  ): Promise<Certificate | null> {
    try {
      return await this.service.updateCertificate({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Certificate)
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "delete",
    possession: "any",
  })
  async deleteCertificate(
    @graphql.Args() args: DeleteCertificateArgs
  ): Promise<Certificate | null> {
    try {
      return await this.service.deleteCertificate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SoftwareProject], { name: "softwareProjects" })
  @nestAccessControl.UseRoles({
    resource: "SoftwareProject",
    action: "read",
    possession: "any",
  })
  async findSoftwareProjects(
    @graphql.Parent() parent: Certificate,
    @graphql.Args() args: SoftwareProjectFindManyArgs
  ): Promise<SoftwareProject[]> {
    const results = await this.service.findSoftwareProjects(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
