/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CertificateService } from "../certificate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CertificateCreateInput } from "./CertificateCreateInput";
import { Certificate } from "./Certificate";
import { CertificateFindManyArgs } from "./CertificateFindManyArgs";
import { CertificateWhereUniqueInput } from "./CertificateWhereUniqueInput";
import { CertificateUpdateInput } from "./CertificateUpdateInput";
import { SoftwareProjectFindManyArgs } from "../../softwareProject/base/SoftwareProjectFindManyArgs";
import { SoftwareProject } from "../../softwareProject/base/SoftwareProject";
import { SoftwareProjectWhereUniqueInput } from "../../softwareProject/base/SoftwareProjectWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CertificateControllerBase {
  constructor(
    protected readonly service: CertificateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Certificate })
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCertificate(
    @common.Body() data: CertificateCreateInput
  ): Promise<Certificate> {
    return await this.service.createCertificate({
      data: data,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Certificate] })
  @ApiNestedQuery(CertificateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async certificates(@common.Req() request: Request): Promise<Certificate[]> {
    const args = plainToClass(CertificateFindManyArgs, request.query);
    return this.service.certificates({
      ...args,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Certificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async certificate(
    @common.Param() params: CertificateWhereUniqueInput
  ): Promise<Certificate | null> {
    const result = await this.service.certificate({
      where: params,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Certificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCertificate(
    @common.Param() params: CertificateWhereUniqueInput,
    @common.Body() data: CertificateUpdateInput
  ): Promise<Certificate | null> {
    try {
      return await this.service.updateCertificate({
        where: params,
        data: data,
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Certificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCertificate(
    @common.Param() params: CertificateWhereUniqueInput
  ): Promise<Certificate | null> {
    try {
      return await this.service.deleteCertificate({
        where: params,
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/softwareProjects")
  @ApiNestedQuery(SoftwareProjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SoftwareProject",
    action: "read",
    possession: "any",
  })
  async findSoftwareProjects(
    @common.Req() request: Request,
    @common.Param() params: CertificateWhereUniqueInput
  ): Promise<SoftwareProject[]> {
    const query = plainToClass(SoftwareProjectFindManyArgs, request.query);
    const results = await this.service.findSoftwareProjects(params.id, {
      ...query,
      select: {
        certificate: {
          select: {
            id: true,
          },
        },

        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        framework: {
          select: {
            id: true,
          },
        },

        handoverDate: true,
        id: true,

        library: {
          select: {
            id: true,
          },
        },

        licenseSubscription: {
          select: {
            id: true,
          },
        },

        technology: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        warrantyEndDate: true,
        warrantyStartDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "update",
    possession: "any",
  })
  async connectSoftwareProjects(
    @common.Param() params: CertificateWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        connect: body,
      },
    };
    await this.service.updateCertificate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "update",
    possession: "any",
  })
  async updateSoftwareProjects(
    @common.Param() params: CertificateWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        set: body,
      },
    };
    await this.service.updateCertificate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Certificate",
    action: "update",
    possession: "any",
  })
  async disconnectSoftwareProjects(
    @common.Param() params: CertificateWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        disconnect: body,
      },
    };
    await this.service.updateCertificate({
      where: params,
      data,
      select: { id: true },
    });
  }
}
