/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FrameworkService } from "../framework.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FrameworkCreateInput } from "./FrameworkCreateInput";
import { Framework } from "./Framework";
import { FrameworkFindManyArgs } from "./FrameworkFindManyArgs";
import { FrameworkWhereUniqueInput } from "./FrameworkWhereUniqueInput";
import { FrameworkUpdateInput } from "./FrameworkUpdateInput";
import { SoftwareProjectFindManyArgs } from "../../softwareProject/base/SoftwareProjectFindManyArgs";
import { SoftwareProject } from "../../softwareProject/base/SoftwareProject";
import { SoftwareProjectWhereUniqueInput } from "../../softwareProject/base/SoftwareProjectWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FrameworkControllerBase {
  constructor(
    protected readonly service: FrameworkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Framework })
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFramework(
    @common.Body() data: FrameworkCreateInput
  ): Promise<Framework> {
    return await this.service.createFramework({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Framework] })
  @ApiNestedQuery(FrameworkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async frameworks(@common.Req() request: Request): Promise<Framework[]> {
    const args = plainToClass(FrameworkFindManyArgs, request.query);
    return this.service.frameworks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Framework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async framework(
    @common.Param() params: FrameworkWhereUniqueInput
  ): Promise<Framework | null> {
    const result = await this.service.framework({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Framework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFramework(
    @common.Param() params: FrameworkWhereUniqueInput,
    @common.Body() data: FrameworkUpdateInput
  ): Promise<Framework | null> {
    try {
      return await this.service.updateFramework({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Framework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFramework(
    @common.Param() params: FrameworkWhereUniqueInput
  ): Promise<Framework | null> {
    try {
      return await this.service.deleteFramework({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/softwareProjects")
  @ApiNestedQuery(SoftwareProjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SoftwareProject",
    action: "read",
    possession: "any",
  })
  async findSoftwareProjects(
    @common.Req() request: Request,
    @common.Param() params: FrameworkWhereUniqueInput
  ): Promise<SoftwareProject[]> {
    const query = plainToClass(SoftwareProjectFindManyArgs, request.query);
    const results = await this.service.findSoftwareProjects(params.id, {
      ...query,
      select: {
        certificate: {
          select: {
            id: true,
          },
        },

        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        framework: {
          select: {
            id: true,
          },
        },

        handoverDate: true,
        id: true,

        library: {
          select: {
            id: true,
          },
        },

        licenseSubscription: {
          select: {
            id: true,
          },
        },

        technology: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        warrantyEndDate: true,
        warrantyStartDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "update",
    possession: "any",
  })
  async connectSoftwareProjects(
    @common.Param() params: FrameworkWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        connect: body,
      },
    };
    await this.service.updateFramework({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "update",
    possession: "any",
  })
  async updateSoftwareProjects(
    @common.Param() params: FrameworkWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        set: body,
      },
    };
    await this.service.updateFramework({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "Framework",
    action: "update",
    possession: "any",
  })
  async disconnectSoftwareProjects(
    @common.Param() params: FrameworkWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        disconnect: body,
      },
    };
    await this.service.updateFramework({
      where: params,
      data,
      select: { id: true },
    });
  }
}
