/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LicenseSubscriptionService } from "../licenseSubscription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LicenseSubscriptionCreateInput } from "./LicenseSubscriptionCreateInput";
import { LicenseSubscription } from "./LicenseSubscription";
import { LicenseSubscriptionFindManyArgs } from "./LicenseSubscriptionFindManyArgs";
import { LicenseSubscriptionWhereUniqueInput } from "./LicenseSubscriptionWhereUniqueInput";
import { LicenseSubscriptionUpdateInput } from "./LicenseSubscriptionUpdateInput";
import { SoftwareProjectFindManyArgs } from "../../softwareProject/base/SoftwareProjectFindManyArgs";
import { SoftwareProject } from "../../softwareProject/base/SoftwareProject";
import { SoftwareProjectWhereUniqueInput } from "../../softwareProject/base/SoftwareProjectWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LicenseSubscriptionControllerBase {
  constructor(
    protected readonly service: LicenseSubscriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LicenseSubscription })
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLicenseSubscription(
    @common.Body() data: LicenseSubscriptionCreateInput
  ): Promise<LicenseSubscription> {
    return await this.service.createLicenseSubscription({
      data: data,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LicenseSubscription] })
  @ApiNestedQuery(LicenseSubscriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async licenseSubscriptions(
    @common.Req() request: Request
  ): Promise<LicenseSubscription[]> {
    const args = plainToClass(LicenseSubscriptionFindManyArgs, request.query);
    return this.service.licenseSubscriptions({
      ...args,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LicenseSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async licenseSubscription(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput
  ): Promise<LicenseSubscription | null> {
    const result = await this.service.licenseSubscription({
      where: params,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LicenseSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLicenseSubscription(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput,
    @common.Body() data: LicenseSubscriptionUpdateInput
  ): Promise<LicenseSubscription | null> {
    try {
      return await this.service.updateLicenseSubscription({
        where: params,
        data: data,
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LicenseSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLicenseSubscription(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput
  ): Promise<LicenseSubscription | null> {
    try {
      return await this.service.deleteLicenseSubscription({
        where: params,
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/softwareProjects")
  @ApiNestedQuery(SoftwareProjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SoftwareProject",
    action: "read",
    possession: "any",
  })
  async findSoftwareProjects(
    @common.Req() request: Request,
    @common.Param() params: LicenseSubscriptionWhereUniqueInput
  ): Promise<SoftwareProject[]> {
    const query = plainToClass(SoftwareProjectFindManyArgs, request.query);
    const results = await this.service.findSoftwareProjects(params.id, {
      ...query,
      select: {
        certificate: {
          select: {
            id: true,
          },
        },

        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        framework: {
          select: {
            id: true,
          },
        },

        handoverDate: true,
        id: true,

        library: {
          select: {
            id: true,
          },
        },

        licenseSubscription: {
          select: {
            id: true,
          },
        },

        technology: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        warrantyEndDate: true,
        warrantyStartDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "update",
    possession: "any",
  })
  async connectSoftwareProjects(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        connect: body,
      },
    };
    await this.service.updateLicenseSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "update",
    possession: "any",
  })
  async updateSoftwareProjects(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        set: body,
      },
    };
    await this.service.updateLicenseSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/softwareProjects")
  @nestAccessControl.UseRoles({
    resource: "LicenseSubscription",
    action: "update",
    possession: "any",
  })
  async disconnectSoftwareProjects(
    @common.Param() params: LicenseSubscriptionWhereUniqueInput,
    @common.Body() body: SoftwareProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      softwareProjects: {
        disconnect: body,
      },
    };
    await this.service.updateLicenseSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }
}
